Neste notebook vamos ler o modelo escolhido da Random Florest

In [1]:
import mlflow
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
import joblib
import mlflow.sklearn

Definir a directoria onde as experiencias são guardadas

In [2]:
from pathlib import Path

uri = "../mlruns"

Path(uri).mkdir(parents=True, exist_ok=True)

mlflow.set_tracking_uri(uri)

In [3]:
# Fazer load da versão do modelo "Random_Forest" que registamos no notebook anterior
# Têm de mudar a versão de acordo com quantas versões registaram.

model_name = "Random_Forest"
model_version = "11"
f"models:/{model_name}/{model_version}"

'models:/Random_Forest/11'

In [4]:
model = mlflow.sklearn.load_model(f"models:/{model_name}/{model_version}")
model

GridSearchCV(cv=5,
             estimator=RandomForestClassifier(class_weight='balanced',
                                              random_state=42),
             param_grid={'n_estimators': [10, 100, 300, 1000]})

Vamos usar o modelo para fazer previsões

In [5]:
data_path = '../data/rumos_bank_test.csv'
df = pd.read_csv(data_path)

In [6]:
input_data = df.loc[df['default.payment.next.month'] == 1].sample(10)
input_data

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default.payment.next.month
5766,40000.0,2,2,1,23,2,2,2,2,2,...,36173.0,36796.0,37288.0,0.0,3200.0,1500.0,1500.0,1400.0,1500.0,1
4711,50000.0,1,3,1,41,4,3,2,0,0,...,27707.0,28479.0,28979.0,0.0,0.0,0.0,974.0,31100.0,1200.0,1
5407,50000.0,1,3,1,46,1,2,2,2,2,...,12601.0,13391.0,14027.0,0.0,2800.0,0.0,1000.0,1000.0,0.0,1
2455,20000.0,2,1,2,23,-1,-1,-1,-1,-1,...,2616.0,600.0,0.0,1283.0,0.0,2616.0,600.0,780.0,1398.0,1
180,130000.0,2,3,1,57,0,0,0,0,0,...,41671.0,42034.0,32219.0,4000.0,4000.0,3000.0,2500.0,1500.0,2000.0,1
4939,90000.0,2,2,2,44,2,2,2,2,2,...,17857.0,20256.0,20785.0,2500.0,2000.0,0.0,2700.0,1000.0,0.0,1
3660,220000.0,2,1,1,42,3,2,2,2,2,...,2500.0,2500.0,2500.0,0.0,0.0,0.0,0.0,0.0,0.0,1
4699,120000.0,2,1,1,42,-1,-1,-1,-1,-1,...,1885.0,607.0,687.0,881.0,1781.0,1885.0,607.0,687.0,1203.0,1
1568,400000.0,2,3,1,41,0,0,0,0,0,...,12620.0,17945.0,20030.0,2620.0,1000.0,0.0,13945.0,7116.0,1280.0,1
892,20000.0,1,1,2,27,1,2,3,2,3,...,7496.0,7231.0,7269.0,3000.0,0.0,800.0,0.0,300.0,0.0,1

In [7]:
input = input_data.drop("default.payment.next.month", axis=1)
colunas=input.columns
input

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
5766,40000.0,2,2,1,23,2,2,2,2,2,...,35704.0,36173.0,36796.0,37288.0,0.0,3200.0,1500.0,1500.0,1400.0,1500.0
4711,50000.0,1,3,1,41,4,3,2,0,0,...,50307.0,27707.0,28479.0,28979.0,0.0,0.0,0.0,974.0,31100.0,1200.0
5407,50000.0,1,3,1,46,1,2,2,2,2,...,13108.0,12601.0,13391.0,14027.0,0.0,2800.0,0.0,1000.0,1000.0,0.0
2455,20000.0,2,1,2,23,-1,-1,-1,-1,-1,...,0.0,2616.0,600.0,0.0,1283.0,0.0,2616.0,600.0,780.0,1398.0
180,130000.0,2,3,1,57,0,0,0,0,0,...,81929.0,41671.0,42034.0,32219.0,4000.0,4000.0,3000.0,2500.0,1500.0,2000.0
4939,90000.0,2,2,2,44,2,2,2,2,2,...,18451.0,17857.0,20256.0,20785.0,2500.0,2000.0,0.0,2700.0,1000.0,0.0
3660,220000.0,2,1,1,42,3,2,2,2,2,...,2500.0,2500.0,2500.0,2500.0,0.0,0.0,0.0,0.0,0.0,0.0
4699,120000.0,2,1,1,42,-1,-1,-1,-1,-1,...,1778.0,1885.0,607.0,687.0,881.0,1781.0,1885.0,607.0,687.0,1203.0
1568,400000.0,2,3,1,41,0,0,0,0,0,...,13010.0,12620.0,17945.0,20030.0,2620.0,1000.0,0.0,13945.0,7116.0,1280.0
892,20000.0,1,1,2,27,1,2,3,2,3,...,6958.0,7496.0,7231.0,7269.0,3000.0,0.0,800.0,0.0,300.0,0.0

In [8]:
scaler = MinMaxScaler()
scaler = joblib.load("scaler.pkl")
input = scaler.transform(input)
input=pd.DataFrame(input, columns = colunas)

In [9]:
input.dtypes

LIMIT_BAL    float64
SEX          float64
EDUCATION    float64
MARRIAGE     float64
AGE          float64
PAY_0        float64
PAY_2        float64
PAY_3        float64
PAY_4        float64
PAY_5        float64
PAY_6        float64
BILL_AMT1    float64
BILL_AMT2    float64
BILL_AMT3    float64
BILL_AMT4    float64
BILL_AMT5    float64
BILL_AMT6    float64
PAY_AMT1     float64
PAY_AMT2     float64
PAY_AMT3     float64
PAY_AMT4     float64
PAY_AMT5     float64
PAY_AMT6     float64
dtype: object

In [10]:
print(model)

GridSearchCV(cv=5,
             estimator=RandomForestClassifier(class_weight='balanced',
                                              random_state=42),
             param_grid={'n_estimators': [10, 100, 300, 1000]})

In [11]:
print(input.dtypes)
print(input.head())

LIMIT_BAL    float64
SEX          float64
EDUCATION    float64
MARRIAGE     float64
AGE          float64
PAY_0        float64
PAY_2        float64
PAY_3        float64
PAY_4        float64
PAY_5        float64
PAY_6        float64
BILL_AMT1    float64
BILL_AMT2    float64
BILL_AMT3    float64
BILL_AMT4    float64
BILL_AMT5    float64
BILL_AMT6    float64
PAY_AMT1     float64
PAY_AMT2     float64
PAY_AMT3     float64
PAY_AMT4     float64
PAY_AMT5     float64
PAY_AMT6     float64
dtype: object
   LIMIT_BAL  SEX  EDUCATION  MARRIAGE       AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0   0.030303  1.0   0.333333  0.333333  0.034483    0.4    0.4    0.4    0.4
1   0.040404  0.0   0.500000  0.333333  0.344828    0.6    0.5    0.4    0.2
2   0.040404  0.0   0.500000  0.333333  0.431034    0.3    0.4    0.4    0.4
3   0.010101  1.0   0.166667  0.666667  0.034483    0.1    0.1    0.1    0.1
4   0.121212  1.0   0.500000  0.333333  0.620690    0.2    0.2    0.2    0.2

   PAY_5  ...  BILL_AMT3  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0    0.4  ...   0.105948   0.194212   0.117134   0.210418  0.000000  0.001900
1    0.2  ...   0.113965   0.186237   0.108887   0.203320  0.000000  0.000000
2    0.4  ...   0.093541   0.172008   0.093926   0.190549  0.000000  0.001662
3    0.1  ...   0.086345   0.162602   0.081243   0.178567  0.001469  0.000000
4    0.2  ...   0.131327   0.199391   0.122328   0.206088  0.004579  0.002375

   PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6
0  0.001674  0.002415  0.003282  0.002846
1  0.000000  0.001568  0.072914  0.002276
2  0.000000  0.001610  0.002345  0.000000
3  0.002920  0.000966  0.001829  0.002652
4  0.003348  0.004026  0.003517  0.003794

[5 rows x 23 columns]

In [12]:
#model.predict(input)
y_probs = model.predict_proba(input)[:, 1]
y_preds = (y_probs > 0.3).astype(int)