Neste notebook vamos ler o modelo escolhido da Random Florest

In [1]:
import mlflow
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
import joblib
import mlflow.sklearn

Definir a directoria onde as experiencias são guardadas

In [2]:
from pathlib import Path

uri = "http://127.0.0.1:5000"



mlflow.set_tracking_uri(uri)

In [3]:
# Fazer load da versão do modelo "Random_Forest" que registamos no notebook anterior
# Têm de mudar a versão de acordo com quantas versões registaram.

model_name = "Random_Forest"
model_version = "11"
f"models:/{model_name}/{model_version}"

'models:/Random_Forest/11'

In [4]:
model = mlflow.sklearn.load_model(f"models:/{model_name}/{model_version}")
model

GridSearchCV(cv=5,
             estimator=RandomForestClassifier(class_weight='balanced',
                                              random_state=42),
             param_grid={'n_estimators': [10, 100, 300, 1000]})

Vamos usar o modelo para fazer previsões

In [5]:
data_path = '../data/rumos_bank_test.csv'
df = pd.read_csv(data_path)

In [6]:
nsamples=10
input_data = df.loc[df['default.payment.next.month'] == 1].sample(nsamples)
input_data

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default.payment.next.month
4328,180000.0,2,2,2,29,0,0,0,2,0,...,142201.0,141826.0,125974.0,11600.0,9635.0,0.0,5245.0,5172.0,3726.0,1
68,50000.0,2,1,2,24,0,0,0,-2,-2,...,0.0,0.0,0.0,7522.0,0.0,0.0,0.0,0.0,0.0,1
4542,30000.0,1,2,1,44,1,3,2,2,2,...,23296.0,22783.0,24310.0,0.0,0.0,1800.0,0.0,1910.0,780.0,1
2978,20000.0,1,2,1,38,0,0,0,0,0,...,14009.0,15773.0,17515.0,3000.0,1210.0,2000.0,2000.0,2000.0,1200.0,1
2701,210000.0,2,1,1,34,-1,-1,-1,-1,-2,...,0.0,0.0,0.0,639.0,699.0,0.0,0.0,0.0,0.0,1
4261,10000.0,1,3,1,37,-1,-1,-1,-1,-1,...,2977.0,1000.0,0.0,602.0,381.0,2986.0,1203.0,0.0,0.0,1
3278,30000.0,2,2,1,44,2,0,0,0,0,...,24336.0,24475.0,24643.0,1662.0,1696.0,1689.0,1016.0,893.0,1100.0,1
3702,320000.0,1,1,1,48,2,2,2,2,2,...,218370.0,220977.0,225021.0,0.0,18300.0,8000.0,7700.0,7700.0,0.0,1
1613,110000.0,1,2,2,51,0,0,0,0,0,...,28858.0,29541.0,27977.0,1400.0,1500.0,1400.0,1000.0,1000.0,760.0,1
2227,60000.0,2,2,2,24,1,-1,3,2,0,...,632.0,316.0,316.0,948.0,0.0,0.0,0.0,316.0,782.0,1

In [7]:
input = input_data.drop("default.payment.next.month", axis=1)
colunas=input.columns
input

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
4328,180000.0,2,2,2,29,0,0,0,2,0,...,180488.0,142201.0,141826.0,125974.0,11600.0,9635.0,0.0,5245.0,5172.0,3726.0
68,50000.0,2,1,2,24,0,0,0,-2,-2,...,0.0,0.0,0.0,0.0,7522.0,0.0,0.0,0.0,0.0,0.0
4542,30000.0,1,2,1,44,1,3,2,2,2,...,21863.0,23296.0,22783.0,24310.0,0.0,0.0,1800.0,0.0,1910.0,780.0
2978,20000.0,1,2,1,38,0,0,0,0,0,...,12219.0,14009.0,15773.0,17515.0,3000.0,1210.0,2000.0,2000.0,2000.0,1200.0
2701,210000.0,2,1,1,34,-1,-1,-1,-1,-2,...,699.0,0.0,0.0,0.0,639.0,699.0,0.0,0.0,0.0,0.0
4261,10000.0,1,3,1,37,-1,-1,-1,-1,-1,...,381.0,2977.0,1000.0,0.0,602.0,381.0,2986.0,1203.0,0.0,0.0
3278,30000.0,2,2,1,44,2,0,0,0,0,...,23343.0,24336.0,24475.0,24643.0,1662.0,1696.0,1689.0,1016.0,893.0,1100.0
3702,320000.0,1,1,1,48,2,2,2,2,2,...,215392.0,218370.0,220977.0,225021.0,0.0,18300.0,8000.0,7700.0,7700.0,0.0
1613,110000.0,1,2,2,51,0,0,0,0,0,...,27871.0,28858.0,29541.0,27977.0,1400.0,1500.0,1400.0,1000.0,1000.0,760.0
2227,60000.0,2,2,2,24,1,-1,3,2,0,...,948.0,632.0,316.0,316.0,948.0,0.0,0.0,0.0,316.0,782.0

In [8]:
scaler = MinMaxScaler()
scaler = joblib.load("scaler.pkl")
input = scaler.transform(input)
input=pd.DataFrame(input, columns = colunas)

In [9]:
input.dtypes

LIMIT_BAL    float64
SEX          float64
EDUCATION    float64
MARRIAGE     float64
AGE          float64
PAY_0        float64
PAY_2        float64
PAY_3        float64
PAY_4        float64
PAY_5        float64
PAY_6        float64
BILL_AMT1    float64
BILL_AMT2    float64
BILL_AMT3    float64
BILL_AMT4    float64
BILL_AMT5    float64
BILL_AMT6    float64
PAY_AMT1     float64
PAY_AMT2     float64
PAY_AMT3     float64
PAY_AMT4     float64
PAY_AMT5     float64
PAY_AMT6     float64
dtype: object

In [10]:
print(model)

GridSearchCV(cv=5,
             estimator=RandomForestClassifier(class_weight='balanced',
                                              random_state=42),
             param_grid={'n_estimators': [10, 100, 300, 1000]})

In [11]:
print(input.dtypes)
print(input.head())

LIMIT_BAL    float64
SEX          float64
EDUCATION    float64
MARRIAGE     float64
AGE          float64
PAY_0        float64
PAY_2        float64
PAY_3        float64
PAY_4        float64
PAY_5        float64
PAY_6        float64
BILL_AMT1    float64
BILL_AMT2    float64
BILL_AMT3    float64
BILL_AMT4    float64
BILL_AMT5    float64
BILL_AMT6    float64
PAY_AMT1     float64
PAY_AMT2     float64
PAY_AMT3     float64
PAY_AMT4     float64
PAY_AMT5     float64
PAY_AMT6     float64
dtype: object
   LIMIT_BAL  SEX  EDUCATION  MARRIAGE       AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0   0.171717  1.0   0.333333  0.666667  0.137931    0.2    0.2    0.2    0.4
1   0.040404  1.0   0.166667  0.666667  0.051724    0.2    0.2    0.2    0.0
2   0.020202  0.0   0.333333  0.333333  0.396552    0.3    0.5    0.4    0.4
3   0.010101  0.0   0.333333  0.333333  0.293103    0.2    0.2    0.2    0.2
4   0.202020  1.0   0.166667  0.333333  0.224138    0.1    0.1    0.1    0.1

   PAY_5  ...  BILL_AMT3  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0    0.2  ...   0.185440   0.294089   0.221278   0.286171  0.013279  0.005721
1    0.0  ...   0.086345   0.160138   0.080648   0.178567  0.008611  0.000000
2    0.4  ...   0.098348   0.182082   0.103239   0.199332  0.000000  0.000000
3    0.2  ...   0.093053   0.173334   0.096288   0.193528  0.003434  0.000718
4    0.0  ...   0.086728   0.160138   0.080648   0.178567  0.000731  0.000415

   PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6
0  0.000000  0.008446  0.012126  0.007068
1  0.000000  0.000000  0.000000  0.000000
2  0.002009  0.000000  0.004478  0.001480
3  0.002232  0.003221  0.004689  0.002276
4  0.000000  0.000000  0.000000  0.000000

[5 rows x 23 columns]

In [12]:
#model.predict(input)
y_probs = model.predict_proba(input)[:, 1]
y_preds = (y_probs > 0.3).astype(int)